# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: عارف فلاح
blog_author: عارف فلاح
email: aref.fallah@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
        توسعه دهنده پایتون / جنگو - طراح وب
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://iamrf.github.io" # the base hostname & protocol for your site, e.g. http://example.com
project_url: "https://github.com/iamrf/iamrf.github.io"

twitter_username: areffallah
github_username:  iamrf
instagram_username: rf.fa
linkedin_username: aref-fallah

#Others
markdown: kramdown

# Syntax highlighting
highlighter: rouge
kramdown:
    input: GFM 
    syntax_highlighter: rouge

# Build settings
#- theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

#   Paginator settings
paginate: 5
paginate_path: "/blog/page:num/"

#   Permalinks allow us to structure the directories of our source code different 
#   from the directories in our output.
#   permalink: /:categories/:year/:month/:day/:title/   # or use >> permalink: pretty
permalink: /:collection/:title/

#   Collections are a great way to group related content like members of a team or 
#   talks at a conference.
collections:
  podcasts:   # set the podcasts collection
    output: true
    permalink: /:collection/:title/
  portfolio:
    output: true
    permalink: /:collection/:title/
  courses:
    output: true
    permalink: /:collection/:title/



#   _includes/follow-buttons.html variables
facebook_url: https:/fb.com/rf.fallah
twitter_url: https://t.co/areffallah
linkedin_url: https://ir.linkedin.com/in/aref-fallah
googleplus_url:
pinterest_url:
instagram_url: https://instagram.com/rf.fa
github_url: https://github.com/iamrf
stackoverflow_url: https://stackoverflow.com/users/9784160/iamrf
